### ISSUE TITLE
Fastladder is incompatible with feedjira 2.0

### ISSUE THREAD

**Issue by ssig33** [fastladder/fastladder#221]
full trace is here

```
feedjira (2.0.0) lib/feedjira/feed.rb:16:in `determine_feed_parser_for_xml'
feedjira (2.0.0) lib/feedjira/feed.rb:8:in `parse'
app/models/feed.rb:50:in `initialize_from_uri'
app/controllers/subscribe_controller.rb:22:in `block in confirm'
app/controllers/subscribe_controller.rb:14:in `each'
app/controllers/subscribe_controller.rb:14:in `confirm'
actionpack (4.2.9) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.9) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.9) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.9) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.9) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.9) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.9) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.9) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.9) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.9) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.9) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.9) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.9) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.9) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.9) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.9) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.9) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.9) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.9) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.9) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.9) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.9) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.9) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.9) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.9) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.9) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.9) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.9) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.9) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.9) lib/action_dispatch/routing/route_set.rb:817:in `call'
rack (1.6.8) lib/rack/etag.rb:24:in `call'
rack (1.6.8) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.8) lib/rack/head.rb:13:in `call'
actionpack (4.2.9) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.9) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.8) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.9) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.9) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.9) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.9) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.9) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.9) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.9) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.9) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.9) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.9) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.9) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.9) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.9) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.9) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.9) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.9) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.9) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.9) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.9) lib/rails/rack/logger.rb:20:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
actionpack (4.2.9) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.8) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.9) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.8) lib/rack/lock.rb:17:in `call'
actionpack (4.2.9) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
railties (4.2.9) lib/rails/engine.rb:518:in `call'
railties (4.2.9) lib/rails/application.rb:165:in `call'
rack (1.6.8) lib/rack/tempfile_reaper.rb:15:in `call'
rack (1.6.8) lib/rack/lint.rb:49:in `_call'
rack (1.6.8) lib/rack/lint.rb:37:in `call'
rack (1.6.8) lib/rack/showexceptions.rb:24:in `call'
rack (1.6.8) lib/rack/commonlogger.rb:33:in `call'
rack (1.6.8) lib/rack/chunked.rb:54:in `call'
rack (1.6.8) lib/rack/content_length.rb:15:in `call'
unicorn (5.1.0) lib/unicorn/http_server.rb:562:in `process_client'
unicorn (5.1.0) lib/unicorn/http_server.rb:658:in `worker_loop'
unicorn (5.1.0) lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
unicorn (5.1.0) lib/unicorn/http_server.rb:519:in `maintain_worker_count'
unicorn (5.1.0) lib/unicorn/http_server.rb:283:in `join'
unicorn (5.1.0) bin/unicorn:126:in `<top (required)>'
/Users/ssig33/.rbenv/versions/2.4.1/bin/unicorn:22:in `load'
/Users/ssig33/.rbenv/versions/2.4.1/bin/unicorn:22:in `<top (required)>'
bundler (1.15.1) lib/bundler/cli/exec.rb:74:in `load'
bundler (1.15.1) lib/bundler/cli/exec.rb:74:in `kernel_load'
bundler (1.15.1) lib/bundler/cli/exec.rb:27:in `run'
bundler (1.15.1) lib/bundler/cli.rb:360:in `exec'
bundler (1.15.1) lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
bundler (1.15.1) lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
bundler (1.15.1) lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
bundler (1.15.1) lib/bundler/cli.rb:20:in `dispatch'
bundler (1.15.1) lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
bundler (1.15.1) lib/bundler/cli.rb:10:in `start'
bundler (1.15.1) exe/bundle:35:in `block in <top (required)>'
bundler (1.15.1) lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
bundler (1.15.1) exe/bundle:27:in `<top (required)>'
/Users/ssig33/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/ssig33/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
```

**Comment by ssig33** [comment]
これ feedjira のせいじゃねえな、Fastladder.simple_fetch が壊れてる
